import express from "express";
import error from "../utils/error";
import bookRouter from "../routes/book.route";
import swaggerUI from "swagger-ui-express";
import swaggerSpec from "../swagger";
const app = express();
app.use(express.json());
app.use(error);
app.use("/api", bookRouter);
app.use("/api-docs", swaggerUI.serve, swaggerUI.setup(swaggerSpec));
export default app;
